### ISSUE TITLE
When searching for LANDs to rent, the "Load more" button is always shown

### ISSUE THREAD

**Issue by LautaroPetaccio** [decentraland/nft-server#162]
## 🎉 Description

When searching for LANDs to rent, the "Load more" button always appears even if there are no more LAND to be shown.

* [x] 🐛 This is a bug report.
* [ ] 📈 This is a feature request.

**Comment by juanmahidalgo** [comment]
@LautaroPetaccio I think this one got fixed by another issue. Can you validate it's not happening anymore? If so, let's close it :)

**Comment by LautaroPetaccio** [comment]
Solved in #170
